### ISSUE TITLE
 I need to configure postgres from aws

### ISSUE THREAD

**Issue by renatovieiradesouza** [iridakos/duckrails#69]
Is possible connect db postgres: aws, gcp or other?

Im try below:

```
 environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_HOSTNAME: "bd-mock-1.testeteste.us-east-1.rds.amazonaws.com"
      DATABASE_PASSWORD: passwd

```

log duck:
https://gist.github.com/renatovieiradesouza/6cf37210535cafb3f658d52bd9dc31f9
